- testrail/helper.py
- closes #22
- Updates singleresult function to detect when an interator has been passed
in, and transform it into a list
> Update singleresult to correctly handle iterators

- testrail/status.py
- tests/test_status.py
> Add full test coverage for Status class

- testrail/api.py
- testrail/client.py
- testrail/plan.py
- testrail/run.py
- tests/test_client.py
- tests/test_plan.py
- tests/test_result.py
- Add to #2 
- Add tests for Plan class
- Add tests for PlanContainer classes
- Minor bug fixes and refactoring associated with tests additions
> Add tests for Plan and PlanContainer classes

- testrail/test.py
> Use correct key when fetching run ID

- testrail/case.py
- testrail/helper.py
I purposely did not add any other classes that have custom fields as I wanted to try it out for a bit.  
@levi-rs does this look like an acceptable approach to you?
I wish there were a way to return the correct type, for example if the value of a field is of a milestone id to return the milestone instance but afaik there is no way of knowing.
> Case custom fields

- testrail/api.py
- testrail/client.py
- testrail/result.py
- tests/test_client.py
- tests/test_result.py
Closes #45 
Update Results query to work with a Run or individual Test.
> 45 get results by run endpoint

- testrail/helper.py
- testrail/result.py
- testrail/test.py
- tests/test_test.py
- Add unit tests for the Test class
> Test unit tests

- testrail/client.py
> take the same API params in Client.__init__ 

- testrail/api.py
- testrail/client.py
- testrail/plan.py
- tests/test_api.py
- tests/test_client.py
- tests/test_plan.py
> Add, update, remove and close Plan

- testrail/api.py
> 56 check status code first

- testrail/api.py
- tests/test_api.py
Add response header information to response error handling to facilitate easier debugging.
> More informative response logging

- testrail/api.py
- Refactor flush_cache to recursively iterate through dicts in `_shared_state` cache and set them to refresh
- Closes #61
> Refactor flush_cache to recursively clear all caches

- README.md
- examples/end_to_end_example.py
Add end to end example of using TestRail python bindings.
> Add example

- testrail/run.py
- tests/test_run.py
Closes #69 
Add Suite setter to Run class.
> Add Suite setter to Run

- testrail/api.py
Update the `_results` cache with new, POSTed result.
As result objects don't have a `project_id` reference, UpdateCache must be updated to handle the results `test_id` reference instead.
> Update _results cache when posting results

- testrail/api.py
- testrail/case.py
- testrail/client.py
- testrail/template.py
@levi-rs could you please give this a quick look over.  It really isn't tested so a second set of eyes is helpful.  I need the functionality asap so that is why I haven't spent much time testing.
> support for adding cases.

- testrail/api.py
- testrail/client.py
- testrail/section.py
Added section methods in client. 
Fixed getting section with id when in multi suite mode
> Get section methods

- testrail/api.py
- tests/test_updatecache.py
Works on #81 
@travispavek, if possible, can you test these out to see if they work for you? I have no tooling in place for adding multiple results or suites.
> 81 additional cache updating

- testrail/api.py
- Write API credentials to class attributes that are available to all
instances
- Closes #103
> 103 Fix missing API credentials

- testrail/api.py
- testrail/test.py
- tests/test_test.py
Fix: return case from test
The case method from the Test class looked for Case in the default suite(suite_id = 10)
> Fix: return case from test

- testrail/api.py
- testrail/client.py
Update Case,
load yaml safer,
fix elapsed time
> Support for updating case

- .travis.yml
- setup.py
- testrail/api.py
- tests/test_api.py
Mock tests need to be updated but merging due to breaking API changes.
> Support bulk get endpoints
